### ISSUE TITLE
Parsing request is failing if it contains brackets

### ISSUE THREAD

**Issue by mike1808** [dmikusa/access_log_parser#2]
It cannot parse request if it contains brackets like this

`GET /?a=fetch&content=<php>die(@md5(HelloThinkCMF))</php> HTTP/1.1`

**Comment by dmikusa** [comment]
Thanks for raising this as well. This is on my TODO list although I didn't create a story. The request path parser I'm using is very strict. It rejects things which are technically not valid, but that you can see in the wild. It needs to be more forgiving for sure.

**Comment by dmikusa** [comment]
I have a fix in for this. It makes the request parser more flexible. It breaks the API though, so I need to cut a new release of this library and pick it up into top-logs which will take a bit longer. Hope to have this out soon though.

https://github.com/dmikusa-pivotal/access_log_parser/commit/c462186bbb6be7e52fd6c17c6e173ff02cb5e6a6

**Comment by dmikusa** [comment]
Top log has been updated. See v1.2.0. It should resolve this for you. Let me know if it doesn't.
